name: Release Test.
on:
  push:
    branches:
      - main
      - develop
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Create .npmrc file
        run: |
          touch .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@knsugiyama:registry=https://npm.pkg.github.com" >> .npmrc
          echo "always-auth=true" >> .npmrc
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
