name: Release Test.
on:
  push:
    branches:
      - main
      - develop
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Create .npmrc file
        run: |
          touch .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_PKG_TOKEN }}" >> .npmrc

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
